# Generated by Django 2.1.7 on 2019-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_title',
            field=models.CharField(default='hello', max_length=400),
            preserve_default=False,
        ),
    ]
